### ISSUE TITLE
Java Script Error

### ISSUE THREAD

**Issue by GREG-YT** [deusprogrammer/dub-editor-electron#6]
got this error. I reinstalled my Windows btw, it worked fine before then.
![Untitled](https://github.com/deusprogrammer/dub-editor-electron/assets/31582101/9802ccc8-4295-4647-8185-78b72026c146)

**Comment by deusprogrammer** [comment]
I’ll take a look :).  It seems to be something to do with the path getting wiped on reinstall.  I’m on vacay now so I will look when I get back.

**Comment by deusprogrammer** [comment]
Found the source of the issue.  Will be patching it shortly.

**Comment by deusprogrammer** [comment]
Pushed changes will release new version in the morning.

**Comment by deusprogrammer** [comment]
If you wouldn't mind, could you confirm if my latest version has fixed your issue?

**Comment by GREG-YT** [comment]
yep it works!

**Comment by deusprogrammer** [comment]
Thank you again for your help =).
